### ISSUE TITLE
FFMPEG - Capture area extends outside window area

### ISSUE THREAD

**Issue by aaronrobertson** [ShareX/ShareX#1433]
Whenever I try to capture with FFMPEG (gif or video) I get this error.
http://imgur.com/szrN6Rh

My screen resolution is 4k (4096x2160), which I suspect has something to do with it, but I'm not sure.
Anyone have any ideas?

**Comment by Jaex** [comment]
Install new ffmpeg version.

**Comment by aaronrobertson** [comment]
Done, worked, thanks!

**Comment by ichpuchtli** [comment]
Hey Guys, How do you update ffmpeg? I downloaded both Shared and Static versions but don't know where ShareX looks for them. Do i just add ffmpeg.exe to front of the $PATH?

**Comment by dannoe** [comment]
@ichpuchtli 
![sharex_2016-07-13_14-04-58](https://cloud.githubusercontent.com/assets/7450586/16802813/ee67620a-4902-11e6-8eb4-256f20bb62ea.png)

**Comment by ichpuchtli** [comment]
@dannoe Legend.

**Comment by lmlikota** [comment]
Thank you @Jaex @dannoe @aaronrobertson 

I have downloaded latest `ffmpeg.exe` using ShareX `download` option but it didn't fix the issue. I've also tried to dowload latest  `ffmpeg.exe` from official site and still no luck. 

Any other ideas? I have Dell U2722DE 4K monitor with resolution 2560x1440 and scaling 125% on Windows 10.

![image](https://user-images.githubusercontent.com/10289319/149318281-435688c2-4063-447d-9cc1-13294e51716f.png)

**Comment by lmlikota** [comment]
Looks like it has something with scaling, after setting default scaling to 100% I've got different issue this time

![image](https://user-images.githubusercontent.com/10289319/149318569-f472ca06-efcd-4f9c-b2fe-887c7f02f96e.png)

**Comment by RaulAlexChavez** [comment]
@lmlikota Where did you  change the default scaling?
I'm having the same problem (already downloaded FFmpeg from website) and would like to try your fix.

**Comment by RaulAlexChavez** [comment]
I found a solution and its pretty easy. Check out this link: https://steamcommunity.com/app/400040/discussions/0/483368526583389012/

**Comment by lmlikota** [comment]
@RaulAlexChavez I have changed my screens scaling to 100% using Windows standard scaling setting. But on scaling 100% everything it too small for my eyes. 
![image](https://user-images.githubusercontent.com/10289319/160589424-4af771f2-d926-49ad-97b6-fd3ee30c04b5.png)

**Comment by lmlikota** [comment]
@RaulAlexChavez Thank you for the fix! Confirming it works. 

![image](https://user-images.githubusercontent.com/10289319/160590099-8ef8d91f-5299-4e86-8c78-2f39420390ec.png)

**Comment by Foadsf** [comment]
You need to `install recorder devices`
