### ISSUE TITLE
Annotation triggered during the capture process

### ISSUE THREAD

**Issue by holodoc** [ShareX/ShareX#2696]
Since 11.9 I am experiencing an issue where the annotation toolbar is displayed during the capture selection phase for regional capture (captures **do not** contain the toolbar). On top of that after the capture zone has been selected the annotation bar disappears and there is nothing that indicates the image has been captured, except it's listed in the main window of the application.

"After capture tasks" is set only to "Annotate image". If I select "Show after capture window" and then select annotate from there, then I get the chance to annotate the image after capture. 

Basically ShareX offers annotation during the regional capture process, which makes no sense or there is something I am potentially not aware of because of all the changes in the recent versions. The annotation toolbar appears as expected if a full screen capture is performed, after not during the capture process.

This basically breaks my entire workflow of quickly annotating images and saving/uploading them.

![sharex](https://user-images.githubusercontent.com/389770/29250819-a57797fc-8049-11e7-8386-f95561a68b63.jpg)

**EDIT:** Rolling back to 11.8.0 resolved the issue partially in a way that the annotation toolbar is still present during capture process (it's still not visible on the captured images) however the annotation is triggered after the regional capture process.

**Comment by Jaex** [comment]
Normally when you annotate in region capture, then after capture tasks annotation not show up. But because of bug in latest version, ShareX thinks you are annotated because of moveable cursor added to screen. So it not shows after capture tasks annotation after region capture. I fixed it 2 days ago.

**Comment by Jaex** [comment]
You can try it if you want using dev builds: https://getsharex.com/docs/dev-builds

**Comment by holodoc** [comment]
Thank your but I prefer to wait for the next official stable release. Until then 11.8.0 will do just fine.

Once again thank you for your time and effort.

**Comment by Jaex** [comment]
Can you enable pre release updates and test is this issue resolved:

![](https://jaex.getsharex.com/2017/08/ShareX_kvnsWQQP3p.png)

**Comment by holodoc** [comment]
I used the pre-release option and the issue seems to be resolved. The toolbar still appears during the selection phase for regional captures, although I still don't understand how it is supposed to be used that way, but I am now getting post-capture annotation.

I've noticed one other peculiar change since 11.9 but in the spirit of GitHub I am going to make a separate issue.

Many thanks for resolving this issue.
