### ISSUE TITLE
unable to upload to imgur

### ISSUE THREAD

**Issue by aaronwi** [ShareX/ShareX#3800]
Message:
Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

doesnt look directly related, but how to debug further?

**Comment by alpinethegreat** [comment]
I'm having the same problem, maybe a server issue?

**Comment by Brian2one0** [comment]
@Jaex wait you develop a program mainly for imgur uploading and imgur is blocked in your country? That's actually hilarious.

**Comment by Jaex** [comment]
Pastebin also blocked too :'(

**Comment by Brian2one0** [comment]
> Pastebin also blocked too :'(

do you live in north korea?

**Comment by Zitzabis** [comment]
Having similar issues with uploading to Imgur. Attempted a ShareX reinstall and updating my Imgur email (based on previous fixes I found). As @Jaex said, sounds like it's an issue on Imgur's end.

**Comment by Jaex** [comment]
> do you live in north korea?

Turkey.

**Comment by invX1** [comment]
Unable to upload, different error though.

(Tried Anonymous Upload, Tried Refreshing Authorization & Tried Reauthorizing)

Message:
The remote server returned an error: (400) Bad Request.
Request URL:
https://api.imgur.com/3/image
Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Zitzabis** [comment]
My errors appeared in the same sequence. I originally got an `An established connection was aborted by the software in your host machine.` error and now it's the `(400) Bad Request`.

**Comment by Zitzabis** [comment]
Issue has been resolved on Imgur's end. You can close this @Jaex

**Comment by TheGamingBolt** [comment]
I'm still getting the same issue.

**Comment by invX1** [comment]
+ Still getting the issue as well.

**Comment by hl2guide** [comment]
Still getting the same issue too:

Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

My Log:

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by StickmansPub** [comment]
I am getting this error as of this morning.

Message:
Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2018-12-08 09:03:58.377 - UploadersConfig save started: C:\Users\Stickman\Documents\ShareX\UploadersConfig.json
2018-12-08 09:03:58.377 - ApplicationConfig save started: C:\Users\Stickman\Documents\ShareX\ApplicationConfig.json
2018-12-08 09:03:58.377 - HotkeysConfig save started: C:\Users\Stickman\Documents\ShareX\HotkeysConfig.json
2018-12-08 09:03:58.537 - HotkeysConfig save successful: C:\Users\Stickman\Documents\ShareX\HotkeysConfig.json
2018-12-08 09:03:58.556 - UploadersConfig save successful: C:\Users\Stickman\Documents\ShareX\UploadersConfig.json
2018-12-08 09:03:58.572 - ApplicationConfig save successful: C:\Users\Stickman\Documents\ShareX\ApplicationConfig.json
2018-12-08 09:06:30.072 - ApplicationConfig save started: C:\Users\Stickman\Documents\ShareX\ApplicationConfig.json
2018-12-08 09:06:30.072 - UploadersConfig save started: C:\Users\Stickman\Documents\ShareX\UploadersConfig.json
2018-12-08 09:06:30.072 - HotkeysConfig save started: C:\Users\Stickman\Documents\ShareX\HotkeysConfig.json
2018-12-08 09:06:30.263 - ApplicationConfig save successful: C:\Users\Stickman\Documents\ShareX\ApplicationConfig.json
2018-12-08 09:06:30.270 - HotkeysConfig save successful: C:\Users\Stickman\Documents\ShareX\HotkeysConfig.json

**Comment by nex86** [comment]
Getting this error:

`Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)`


I can upload pictures on the imgur website just fine.

**Comment by stuntguy3000** [comment]
This issue is caused by Imgur's image API service not functioning correctly. Unfortunately this is not a ShareX problem and we have no control over resolving this issue. Please be patient and wait for this issue to be resolved by Imgur themselves.

**Comment by Zellogi** [comment]
How about this one?

Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

Request URL:
https://puush.me/api/up

Stack trace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Zitzabis** [comment]
@Zellogi That would fall under a new issue since it's not Imgur.
