### ISSUE TITLE
Installation for non-admins

### ISSUE THREAD

**Issue by mythofechelon** [ShareX/ShareX#5033]
It's cybersecurity best practice for everyday user accounts to **not** have administrative permissions so that if / when they become compromised then the scope of damage is significantly limited.

Even as of version 13.2.1 (latest as of writing), using a standard / non-admin user account to install ShareX has a few problems:
	1. The installer doesn't auto-elevate so all the user sees is `Error 5: Access is denied.`
	2. The final option `Launch ShareX` uses the admin account's profile, not the standard account that initiated the installation, which has completely separate settings, task history, etc.

Below is an example of this:
![2020 ∕ 09 ∕ 11 19꞉13꞉06](https://user-images.githubusercontent.com/28054556/92959225-54cecc80-f463-11ea-8fac-f38bd3def37c.gif)

**Comment by McoreD** [comment]
You appear to have disabled UAC? Simply double clicking the installer should prompt UAC by default.

**Comment by mythofechelon** [comment]
Nope, as you can see below:
![2020 ∕ 09 ∕ 12 23꞉32꞉25 - User_Account_Control_Settings](https://user-images.githubusercontent.com/28054556/93006118-44e0e680-f550-11ea-82da-d3599113607d.png)

**Comment by McoreD** [comment]
Thanks for confirming. Instead of Run As Administrator, can you please try double clicking setup to install?
Unfortunately the installer is working as expected in your video because you installed after inputting Administrator credentials.

**Comment by mythofechelon** [comment]
You can see in the GIF / video that the first installation attempt was by double clicking.

**Comment by rjlan** [comment]
I have similar issue where after updating it launches under the administrator account instead of user account

**Comment by Jaex** [comment]
> I have similar issue where after updating it launches under the administrator account instead of user account

It is fixed in latest version.

**Comment by mythofechelon** [comment]
I just experienced this problem while updating from version 13.3.0 to version 13.4.0.

**Comment by mythofechelon** [comment]
I just experienced this problem while updating from version 13.4.0 to version 13.5.0.

**Comment by mythofechelon** [comment]
I just experienced this problem while installing version 13.6.1.

**Comment by RainerZufahl** [comment]
This is still an issue when updating to 13.7.0. The updater doesn't ask for elevated permissions before starting the install, and results in a Error 5 because of it. Futhermore, since it is not shown where the updater is downloaded to, I am now frantically looking through all my temp folders in search of it, so i can manually launch with admin privileges.

**Comment by CompeyDev** [comment]
Similar error, doesn't ask for admin perms and hence install fails. Either way, I do not have admin perms, so it would not work. Any fixes?

**Comment by SebAtMinalea** [comment]
It would indeed be nice to allow non admins to install and update ShareX, where do I vote? :-D

**Comment by joelhellman** [comment]
Same here, it doesn't trigger UAC on my setup and errors out during install (and rolls back install, which is nice). I can invoke setup as admin, but that obviously requires admin permissions, and in my case, admin user is a separate user, so I then have to go in and change profile etc paths post-install, so it points to my standard user. 

I'd also love if app could support users installs that doesn't need admin permissions.

**Comment by mythofechelon** [comment]
I just experienced this problem while installing version 14.0.1.

**Comment by McoreD** [comment]
> I just experienced this problem while installing version 14.0.1.

You will continue to have this issue. There is outlook to fix this at the setup level. Your only option is to fork it and change the setup like I have done for our organisation: https://github.com/McoreD/ShareX/issues/1 while we continue to maintain the default way unchanged for our ShareX repository.
