### ISSUE TITLE
Tray icon middle click setting does not work

### ISSUE THREAD

**Issue by xNiika** [ShareX/ShareX#6846]
I changed `Application settings > General > On tray icon middle click` to `Upload from clipboard with content viewer`.

If I do a middle click on the tray icon, the action `Capture region` is always executed instead, so the setting does nothing.

**Comment by miyagui** [comment]
same problem.

**Comment by Flawedspirit** [comment]
Anyone looking into this?

**Comment by Adam-Kay** [comment]
This happened for me upon upgrading from Windows 10 to Windows 11 I believe.

**Comment by Hill-98** [comment]
This is a known issue in Windows 11 (<https://techcommunity.microsoft.com/t5/windows-11/windows-11-build-22621-1344-and-later-broke-the-ability-to/m-p/3774219>), so fixing it isn't that easy and may require some kind of Hook.

What do you think about this? @Jaex

**Comment by henrypp** [comment]
@Hill-98 

it was fixed in win11 24h2 26100+, M$ was slowpoke, it required 3.5 years to fix this problem, lol

**Comment by Jaex** [comment]
Duplicate of #6791

**Comment by henrypp** [comment]
> it was fixed in win11 24h2 26100+

lol, in 26100.1876 same as in pre-23h2, M$ was stupid idiots...

<s>ps: in 26100.2454 back to normal, idk what, but it changed!</s>

ps2: 26100.2894 is last working, others is processing middle-click as left-click, M$ stupid cunts!

**Comment by gazchap** [comment]
This problem still occurs for me, and I'm already on Win11 24H2 (26100.4349 specifically) ?

**Comment by henrypp** [comment]
@gazchap 

24h2 is stupid bullshit, update to 25h2, 26200.5651 dont have this stupid problem!
