### ISSUE TITLE
ShareX complains failing to find a path when uploading contents of clipboard

### ISSUE THREAD

**Issue by Twister915** [ShareX/ShareX#963]
I had text copied to my clipboard, and typically can hit my "upload clipboard" keyboard shortcut, which is control+shift+5, and expect the content to be uploaded to my custom uploader (as a file with content type plain/text).

However, I have gotten this error with copied text repeatedly when trying to upload it

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Electric\Documents\ShareX\Screenshots\2015-09\2015-09-01_22-03-13.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at ShareX.UploadTask.DoTextJobs()
   at ShareX.UploadTask.DoThreadJob()
   at ShareX.UploadTask.ThreadDoWork()
   at ShareX.HelpersLib.ThreadWorker.WorkThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Twister915** [comment]
I determined this problem to be resolved by creating the directory `2015-09` manually.

One would expect ShareX to create this directory automatically when the upload is attempted.

**Comment by Jaex** [comment]
#960, #947, #937, #908, #900, #870, #860, #847

**Comment by McoreD** [comment]
Thank you for reporting this issue. We are already fixed this in our current release.

**Comment by davidruhmann** [comment]
General question to @Jaex or @McoreD is there a release strategy for ShareX? Milestones? Schedule? or is it just released as desired?

**Comment by Jaex** [comment]
Mainly I release after one month because some people don't like frequent updates.
But if after one month still have very few features and not worth releasing yet then I will wait little more.
After release If people report important bug then I will release bug fix build.
Currently I wrote change log already and doing last checks to make sure everything allright. Will probably release in two days. Hopefully that BaseForm changes not broken anything :)
By the way you can add me to messenger like Steam, Google Talk etc. if you want.

**Comment by davidruhmann** [comment]
@Jaex thanks for the info.  Does Google Talk still exist?  Hangouts or IRC would probably work best for me.

**Comment by Jaex** [comment]
Hangouts is Google Talk for me because I'm using Trillian.
In https://getsharex.com you can use contact form to send your google talk email to me.

**Comment by Twister915** [comment]
Thanks, just saw this now. :+1:
